--- # Run with:  ansible-playbook proxmoxve_install.yaml -i hosts
- name: Install proxmox
  hosts: "{{ target | lower }}"
  become: true
  gather_facts: yes
  vars:
    resolvlines: 
      - regex:  '^domain'
        replace: 'domain lab.test.'
      - regex:  '^search'
        replace: 'search lab.test.'
    pvkeyring:   '/etc/apt/trusted.gpg.d/proxmox-ve-no-subscription.asc'
    postfixdebconf:
      - question: 'postfix/bad_recipient_delimiter' 
        vtype:    'error'
        value:    ''
      - question: 'postfix/chattr'
        vtype:    'boolean'
        value:    'false'
      - question: 'postfix/destinations'
        vtype:    'string'
        value:    "$myhostname, {{ target }}.lab.test, localhost.lab.test, localhost"
      - question: 'postfix/mailbox_limit'
        vtype:    'string'
        value:    '0'
      - question: 'postfix/mailname'
        vtype:    'string'  
        value:    'hpt730-3.lab.test'
      - question: 'postfix/main_mailer_type'
        vtype:    'select'
        value:    'Local only'
      - question: 'postfix/mynetworks'
        vtype:    'string'
        value:    '127.0.0.0/8 [::ffff:127.0.0.0]/104 [::1]/128'
      - question: 'postfix/newaliases'
        vtype:    'boolean'
        value:    'false'
      - question: 'postfix/not_configured'
        vtype:    'error'
        value:    ''
      - question: 'postfix/procmail'
        vtype:    'boolean'
        value:    'false'
      - question: 'postfix/protocols'
        vtype:    'select'
        value:    'all'
      - question: 'postfix/recipient_delim'
        vtype:    'string'
        value:    '+'
      - question: 'postfix/relayhost'
        vtype:    'string'
        value:    ''
      - question: 'postfix/rfc1035_violation'
        vtype:    'boolean'
        value:    'false'
      - question: 'postfix/root_address'
        vtype:    'string'
        value:    ''

  vars_prompt:
    - name: target
      prompt: Which host would you like to install Proxmox VE on?
      private: no

  tasks:
    - name: Install common packages we may need
      ansible.builtin.apt:
        name:
          - gnupg
          - debconf-utils
          - vim
          - ansible
          - screen
        state: present

    - name: Remove any localhost entries from /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: absent
        regexp: '^127\.?\.?\.?'

    - name: Add localhost back to /etc/hosts
      ansible.builtin.lineinfile:
        path: /etc/hosts
        state: present
        line: '127.0.0.1       localhost'
        insertbefore: 'BOF'

    - name: Verify domain has proper search parameters
      ansible.builtin.lineinfile:
        path: /etc/resolv.conf
        state: present
        regexp: "{{ item.regex }}"
        line:   "{{ item.replace }}"
        insertafter: "EOF"
      loop: "{{ resolvlines }}"

    - name: Create keyring if it doesn't exist
      ansible.builtin.file:
        path: "{{ pvkeyring }}"
        state: touch
        owner: root
        group: root
        mode: "u=rw,go=r"

    - name: Add the signature key for the Proxmox VE repository
      ansible.builtin.apt_key:
        url: https://enterprise.proxmox.com/debian/proxmox-release-bookworm.gpg
        keyring: "{{ pvkeyring }}"
        state: present
        
    - name: Add repository for Proxmox VE Community Edition
      ansible.builtin.apt_repository:
        filename: pve-no-subscription
        repo: deb http://download.proxmox.com/debian/pve bookworm pve-no-subscription
        state: present

    - name: Install the Proxmox kernel
      ansible.builtin.apt:
        name: pve-kernel-6.2
        state: present
        update_cache: true

    - name: Update grub to add new pve kernel
      ansible.builtin.shell: update-grub

    - name: Reboot the system into the new proxmox kernel
      ansible.builtin.reboot:
        reboot_timeout: 300

    - name: Remove the old debian kernel
      ansible.builtin.apt:
        name: 
          - 'linux-image-amd64'
          - 'linux-image-6.1*'
        state: absent
        
    - name: Update grub to remove old debian kernels
      ansible.builtin.shell: update-grub

    - name: Reboot the system again after removing the old kernel
      ansible.builtin.reboot:
        reboot_timeout: 300

    - name: Preconfigure postfix
      ansible.builtin.debconf:
        name:     'postfix'
        question: "{{ item.question }}"
        value:    "{{ item.value }}"
        vtype:    "{{ item.vtype }}"
      loop: "{{ postfixdebconf }}"

    - name: Install Proxmox VE Packages
      ansible.builtin.apt:
        name:
          - 'open-iscsi'
          - 'postfix'
          - 'proxmox-ve'

    - name: Remove the pve-enterprise.list source
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/pve-enterprise.list"
        state: absent

    - name: Remove OS prober
      ansible.builtin.apt:
        name: os-prober
        state: absent

    - name: Install ntpsec
      ansible.builtin.apt:
        name: ntpsec
        state: present
